ren twentyeleven*.zip twentyeleven.zip
ren twentyfifteen*.zip twentyfifteen.zip
ren twentyfourteen*.zip twentyfourteen.zip
ren twentynineteen*.zip twentynineteen.zip
ren twentyseventeen*.zip twentyseventeen.zip
ren twentysixteen*.zip twentysixteen.zip
ren twentyten*.zip twentyten.zip
ren twentythirteen*.zip twentythirteen.zip
ren twentytwelve*.zip twentytwelve.zip
ren twentytwenty*.zip twentytwenty.zip
ren twentytwentyone*.zip twentytwentyone.zip
ren twentytwentytwo*.zip twentytwentytwo.zip
ren phpMyAdmin*.tar.gz phpMyAdmin.tar.gz
ren wordpress*.tar.gz wordpress.tar.gz
